In [1]:
import pandas as pd
df1 = pd.read_excel('comp.xlsx', header = None, names = ["ticker", "eps", "revenue", "price", "people"])

In [2]:
df1.to_csv('company.csv', index = False, columns = ['eps', 'revenue'])

In [3]:
df2 = pd.read_csv("weather.csv")
df2.head()

          day  temperature  windspeed   event
0  01-01-2017           32          6    rain
1  01-02-2017           35          7  sunny
2  01-03-2017           28          2    snow
3  01-04-2017           24          7    snow
4  01-05-2017           32          4    rain

In [4]:
with pd.ExcelWriter('weather_company.xlsx') as writer:
    df1.to_excel(writer, sheet_name = 'company', index = False)
    df2.to_excel(writer, sheet_name = 'weather', index = False)

In [14]:
df = pd.read_csv('weather.csv', index_col = False)
df.head()

          day  temperature  windspeed   event
0  01-01-2017           32          6    rain
1  01-02-2017           35          7  sunny
2  01-03-2017           28          2    snow
3  01-04-2017           24          7    snow
4  01-05-2017           32          4    rain

In [16]:
df.to_csv('weather2.csv', index=False)

In [17]:
df_2 = pd.read_csv('weather2.csv')
df_2.head()

          day  temperature  windspeed   event
0  01-01-2017           32          6    rain
1  01-02-2017           35          7  sunny
2  01-03-2017           28          2    snow
3  01-04-2017           24          7    snow
4  01-05-2017           32          4    rain